app:
  base-url: ${APP_BASE_URL}

spring:
  application:
    name: enquete
  datasource:
    url: ${DATABASE_URL}
    hikari:
      connection-init-sql: SET TIME ZONE 'UTC'
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
  security:
    oauth2:
      authorization-server:
        issuer-uri: ${app.base-url}
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  thymeleaf:
    cache: true